### ISSUE TITLE
Несоответствие имен классов/пакетов/переменных Java Naming Convention

### ISSUE THREAD

**Issue by kubikrubikvkube** [AzarovaLena/AutomationProject_Azarova_Lena#11]
Нашёл Ваше объявление о поиске работы на LinkedIn, исключительно из интереса зашёл сюда, и хотел бы порекомендовать Вам по возможности следовать вот этим правилам: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html , это создаст хорошее первое впечатление о Вашем проекте.
Удачи!

**Comment by AzarovaLena** [comment]
Спасибо за помощь)
